import type { Product } from "./cart-context"

export const products: Product[] = [
  {
    id: "led-wall-30x15",
    name: "Large Retail Showcase LED Wall",
    slug: "large-retail-showcase-led-wall-30x15",
    description:
      "Massive 30' x 15' professional LED video wall perfect for large venues, sports bars, and outdoor fan festivals. Features stunning 4K resolution with HDR support, ideal for FIFA World Cup viewing parties with crystal-clear action replay.",
    dimensions: "30' x 15' (450 sq ft)",
    price: 8999,
    originalPrice: 9999,
    discount: 10,
    image: "/images/products/led-wall-30x15.webp",
    features: [
      "4K Ultra HD Resolution",
      "HDR10+ Support",
      "Outdoor IP65 Rated",
      "500+ Guests Capacity",
      "Novastar Processing",
    ],
    specs: {
      pixelPitch: "P2.6mm",
      resolution: "3840 x 1920",
      brightness: "5500 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (120 units)",
      "Novastar VX6s Processor",
      "Flight Cases (4)",
      "Power Distribution",
      "Signal Cables",
      "Ground Support Truss",
    ],
    deliveryFee: 1200,
    installationFee: 2500,
    rentalPeriod: "24h",
    inStock: true,
    featured: true,
  },
  {
    id: "led-wall-25x15",
    name: "Immersive Exhibition Screen",
    slug: "immersive-exhibition-screen-25x15",
    description:
      "Premium 25' x 15' LED wall designed for corporate events, trade shows, and high-end watch parties. Perfect for World Cup finals viewing with immersive visual experience.",
    dimensions: "25' x 15' (375 sq ft)",
    price: 7499,
    originalPrice: 8299,
    discount: 10,
    image: "/images/products/led-wall-25x15.webp",
    features: [
      "4K Ultra HD Resolution",
      "Seamless Panel Design",
      "Indoor/Outdoor Use",
      "400+ Guests Capacity",
      "Quick Assembly",
    ],
    specs: {
      pixelPitch: "P2.9mm",
      resolution: "3200 x 1600",
      brightness: "5000 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (100 units)",
      "Novastar VX4S Processor",
      "Flight Cases (3)",
      "Power Distribution",
      "Signal Cables",
      "Ground Support",
    ],
    deliveryFee: 1000,
    installationFee: 2000,
    rentalPeriod: "24h",
    inStock: true,
  },
  {
    id: "led-wall-25x12",
    name: "Main Entrance LED Wall",
    slug: "main-entrance-led-wall-25x12",
    description:
      "Stunning 25' x 12' LED video wall ideal for venue entrances, lobbies, and medium-sized sports viewing events. Delivers broadcast-quality visuals for up to 300 guests.",
    dimensions: "25' x 12' (300 sq ft)",
    price: 5999,
    originalPrice: 6599,
    discount: 9,
    image: "/images/products/led-wall-25x12.webp",
    features: [
      "Broadcast Quality",
      "Easy Modular Setup",
      "High Brightness",
      "300+ Guests Capacity",
      "Weather Resistant",
    ],
    specs: {
      pixelPitch: "P2.9mm",
      resolution: "2880 x 1440",
      brightness: "4500 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (80 units)",
      "Novastar VX4S Processor",
      "Flight Cases (3)",
      "Power Distribution",
      "Signal Cables",
    ],
    deliveryFee: 850,
    installationFee: 1800,
    rentalPeriod: "24h",
    inStock: true,
  },
  {
    id: "led-wall-15x8",
    name: "Lobby Information Screen",
    slug: "lobby-information-screen-15x8",
    description:
      "Professional 15' x 8' LED display perfect for hotel lobbies, restaurant watch parties, and corporate viewing rooms. Excellent for groups of 100-200 viewers.",
    dimensions: "15' x 8' (120 sq ft)",
    price: 3499,
    originalPrice: 3899,
    discount: 10,
    image: "/images/products/led-wall-15x8.webp",
    features: [
      "Crystal Clear Display",
      "Quick Setup (2hrs)",
      "Low Power Consumption",
      "150+ Guests Capacity",
      "Silent Operation",
    ],
    specs: {
      pixelPitch: "P2.6mm",
      resolution: "1920 x 1024",
      brightness: "4000 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (48 units)",
      "Novastar VX2 Processor",
      "Flight Cases (2)",
      "Power Distribution",
      "Signal Cables",
    ],
    deliveryFee: 500,
    installationFee: 1200,
    rentalPeriod: "24h",
    inStock: true,
    featured: true,
  },
  {
    id: "led-wall-8x5",
    name: "Compact LED Screen",
    slug: "compact-led-screen-8x5",
    description:
      "Versatile 8' x 5' LED screen ideal for smaller venues, private viewing rooms, and backyard watch parties. Perfect for intimate groups of 30-80 guests.",
    dimensions: "8' x 5' (40 sq ft)",
    price: 1599,
    originalPrice: 1799,
    discount: 11,
    image: "/images/products/led-wall-8x5.webp",
    features: [
      "Portable Design",
      "Fast Setup (1hr)",
      "High Resolution",
      "80 Guests Capacity",
      "Plug & Play",
    ],
    specs: {
      pixelPitch: "P2.9mm",
      resolution: "960 x 600",
      brightness: "3500 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (20 units)",
      "Novastar VX1 Processor",
      "Flight Case (1)",
      "Power Distribution",
      "HDMI/SDI Cables",
    ],
    deliveryFee: 250,
    installationFee: 600,
    rentalPeriod: "24h",
    inStock: true,
  },
  {
    id: "led-wall-8x4",
    name: "Patient Waiting Area Display",
    slug: "patient-waiting-area-display-8x4",
    description:
      "Compact 8' x 4' LED display designed for waiting areas, small bars, and intimate viewing spaces. Great value for small group watch parties.",
    dimensions: "8' x 4' (32 sq ft)",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    image: "/images/products/led-wall-8x4.webp",
    features: [
      "Space Efficient",
      "Ultra Fast Setup",
      "Energy Efficient",
      "50 Guests Capacity",
      "Mobile Friendly",
    ],
    specs: {
      pixelPitch: "P2.9mm",
      resolution: "960 x 480",
      brightness: "3500 nits",
      refreshRate: "3840Hz",
      viewingAngle: "160°",
      lifespan: "100,000 hours",
    },
    includes: [
      "LED Panels (16 units)",
      "Novastar VX1 Processor",
      "Flight Case (1)",
      "Power Distribution",
      "HDMI Cable",
    ],
    deliveryFee: 200,
    installationFee: 500,
    rentalPeriod: "24h",
    inStock: true,
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}
